services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${LOCAL_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASS}
      PORTGRES_DB: ${LOCAL_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local